
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Linux -  - 
      The host system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /mnt/e/HMOS_SDK/linux/native/llvm/bin/aarch64-unknown-linux-ohos-clang 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      /mnt/e/HMOS_SDK/linux/native/llvm/bin/lld: error while loading shared libraries: /mnt/e/HMOS_SDK/linux/native/llvm/bin/../lib/libxml2.so.16: file too short
      clang-15: error: unable to execute command: No such file or directory
      clang-15: error: linker command failed due to signal (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /mnt/e/HMOS_SDK/linux/native/llvm/bin/aarch64-unknown-linux-ohos-clang 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is Clang, found in:
        /mnt/e/projects/qemu-hmos/entry/src/main/cpp/build-test/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /mnt/e/HMOS_SDK/linux/native/llvm/bin/aarch64-unknown-linux-ohos-clang++ 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      /mnt/e/HMOS_SDK/linux/native/llvm/bin/lld: error while loading shared libraries: /mnt/e/HMOS_SDK/linux/native/llvm/bin/../lib/libxml2.so.16: file too short
      clang-15: error: unable to execute command: No such file or directory
      clang-15: error: linker command failed due to signal (use -v to see invocation)
      
      
